Repository divyanshudhruv/Minifolio, pull requests merged in 2023-10, with the labels that each got.

#33 Footer Enhanced ( Copyright with Year added & Fully Responsive )
  index.html
  js/copyRight.js
  style.css
Labels: hacktoberfest-accepted, 🎉 Hacktoberfest, ⏰ Merging

#40 Resolved Issue #39
  button.css
  css/style.css
  index.html
  style.css
Labels: 🎉 Hacktoberfest, ⏰ Merging

#38 Solve Fixes : #21 Add Terminal typing to role
  css/style.css
  index.html
  js/typingAnimation.js
Labels: 🔥 Enhancement, 🎉 Hacktoberfest

#48 Made button appear at new Line in Smartphone View
  css/button.css
  css/style.css
  index.html
Labels: 🔥 Enhancement, hacktoberfest-accepted, 🎉 Hacktoberfest, 🔒 Closed

#50 Added Back To Top Button
  css/button.css
  index.html
  js/script.js
Labels: ✨ New Feature, 🎉 Hacktoberfest

#61 Enhance footer section
  css/style.css
  index.html
Labels: 🔥 Enhancement, hacktoberfest-accepted, 🎉 Hacktoberfest

#62 Add page loading animation
  README.md
  css/button.css
  css/preloader.css
  index.html
  js/preloader.js
Labels: hacktoberfest-accepted, ✨ New Feature, 🎉 Hacktoberfest

#68 chore: add 404 page
  404.html
  css/button.css
  js/404.js
Labels: ✨ New Feature, 🎉 Hacktoberfest

#86 Added Project Section
  assets/checkmark.png
  assets/project-1.png
  assets/project-2.png
  assets/project-3.png
  css/style.css
  index.html
Labels: hacktoberfest-accepted, ✨ New Feature, 🎉 Hacktoberfest, ⏰ Merging
