Repository divyanshudhruv/Minifolio, pull requests merged in 2024-10, with the labels that each got.

#98 Add services section
  404.html
  css/404.css
  css/button.css
  css/style.css
  index.html
Labels: 🔥 Enhancement, hacktoberfest-accepted, 🎉 Hacktoberfest, ⏰ Merging

#119 Education Timeline
  css/style.css
  index.html
Labels: 🔥 Enhancement, 🎉 Hacktoberfest, ⏰ Merging, 🆕 new

#128 Add extra styles for main button
  css/style.css
Labels: 🔥 Enhancement, hacktoberfest-accepted, 🎉 Hacktoberfest, ⏰ Merging

#117 Logo of Minifolio
  css/navbar.css
  css/style.css
  js/script.js
  logo/minifolio.ico
  logo/minifolio.png
  logo/minifolio.svg
Labels: hacktoberfest-accepted, 🎉 Hacktoberfest, ⏰ Merging, 🆕 new, 🚀 New Addition

#132 Added the project section
  css/navbar.css
  css/style.css
  index.html
  js/script.js
  logo/minifolio.ico
  logo/minifolio.png
  logo/minifolio.svg
Labels: 🔥 Enhancement, hacktoberfest-accepted, 🎉 Hacktoberfest, ⏰ Merging, 🆕 new

#126 Implement the project section
  assets/project1.png
  assets/project2.png
  assets/project3.png
  css/navbar.css
  css/style.css
  index.html
  js/script.js
  logo/minifolio.ico
  logo/minifolio.png
  logo/minifolio.svg
Labels: 🔥 Enhancement, hacktoberfest-accepted, 🎉 Hacktoberfest, ⏰ Merging

#97 Enhanced the footer UI
  css/style.css
  index.html
Labels: 🔥 Enhancement, hacktoberfest-accepted, 🎉 Hacktoberfest, 🆕 new

#103 Added Project section
  css/style.css
  index.html
Labels: 🔥 Enhancement, hacktoberfest-accepted, 🎉 Hacktoberfest, 🆕 new

#153 Add "Education" to the nav bar
  index.html
Labels: hacktoberfest-accepted, 🎉 Hacktoberfest, ⏰ Merging, 🆕 new

#155 Added a new contact form.
  LICENSE
  css/style.css
  index.html
Labels: 🔥 Enhancement, hacktoberfest-accepted, 🎉 Hacktoberfest, 🔒 Closed, ⏰ Merging

#122 profile-pic added and project section added
  css/button.css
  css/projectsec.css
  css/style.css
  index.html
  portfolioimg.jpg
Labels: 🆕 new

#111 Added a Hamburger Navigation Bar
  css/style.css
  index.html
Labels: 🔥 Enhancement, hacktoberfest-accepted, 🚧 Help Wanted, 🎉 Hacktoberfest, 🆕 new

#159 Add the Gsap animation on the home page , Add custom cursor that follow whole page
  css/style.css
  images/img1.png
  images/img2.png
  images/img3.png
  index.html
  js/cursor.js
  js/script.js
Labels: ✨ New Feature, 🎉 Hacktoberfest

#154 Added blog section to portfolio with HTML, CSS & JAVASCRIPT
  blogsection.html
  css/blogSection.css
  css/style.css
  index.html
  js/blog.js
  js/script.js
Labels: 🎉 Hacktoberfest, ⏰ Merging, 🆕 new

#187 🔥 Enhancement : Add social icons
  README.md
  css/button.css
  css/style.css
  index.html
  js/script.js
Labels: 🔥 Enhancement, hacktoberfest-accepted, 🎉 Hacktoberfest

#184 Added Resume Button
  README.md
  css/button.css
  css/navbar.css
  css/style.css
  images/facebook.png
  images/link.png
  images/linkedin.png
  images/twitter.png
  index.html
Labels: hacktoberfest-accepted, 🎉 Hacktoberfest

#195 Refined the footer layout
  README.md
  css/button.css
  css/navbar.css
  css/style.css
  index.html
  js/script.js
Labels: hacktoberfest-accepted, 🎉 Hacktoberfest, 🔒 Closed

#194 issue resolved #191 real time name change and also added some styling
  css/style.css
  homesection.js
  index.html
  js/script.js
Labels: hacktoberfest-accepted, ✨ New Feature, 🎉 Hacktoberfest, 🔒 Closed, 🆕 new, ⚙️ in-progress

#175 experience section
  css/style.css
  index.html
  js/script.js
Labels: hacktoberfest-accepted, 🎉 Hacktoberfest, 🔒 Closed

#197 Fixes: #181 Added Footer section in Site
  css/navbar.css
  css/style.css
  index.html
Labels: 🔥 Enhancement, 🎉 Hacktoberfest, ⏰ Merging, ☢️ critical

#206 footer modified
  README.md
  css/button.css
  css/navbar.css
  css/sd.css
  css/style.css
  index.html
  js/script.js
Labels: hacktoberfest-accepted, 🎉 Hacktoberfest, ⏰ Merging, ☢️ critical
